### PR TITLE
Added DataSet2 to the project. Dimension creation function now draws …

### PR DESCRIPTION
**Pull request by MattyJP**
Added DataSet2 to the project. Dimension creation function now draws from both datasets.
Since multiple entries in DataSet2 are improperly formatted (with some lacking profit data due to this), the SQl function to pull from this dataset excludes any improperly-formatted entries.
This works by checking if the default-named columns (In this case,  Field22) is empty. If the column is empty, the row is correctly formatted and will be added to the dimensions and fact table.

Main changes are to Form1, involving creation of multiple connectionStrings and duplicated, modified versions of the initial Sheet1 Sql command to check for null fields.

Postal Code in Form1 no longer treated as Int32 for creation of Customer dimension due to DataSet2's values containing alphabetical characters and spaces to represent UK post codes..

### CODE REVIEW

**Comment by CLucas96** [comment]
Issues: 
- Double clicking buttons "Get Customers", "Get Dates","Get Product" tries to use Clear Method but crashes. and causes the system to crash. 
- "Populate Fact Table" Causes system to throw error on line 620 of Form.cs

**Comment by CLucas96** [comment]
Other than the issues stated above, system works fine and is functional. once issues are fixed the pull request can be merged with no conflicts

**Comment by MattyJP** [comment]
-"Double clicking buttons "Get Customers", "Get Dates","Get Product" tries to use Clear Method but crashes. and causes the system to crash."

Appears to be an issue present in previous builds. Can be resolved in a later branch. Low priority because the button would only need to be clicked once (Potential solution: Disable dimension button after initial press)

Pushing a version where the dimension buttons are disabled after initial creation, will need testing to see if things improve.

**Comment by CLucas96** [comment]
Thanks for pushing fixes so quickly, BUttons are now disabled after initial click, the "Get DB" Button refreshes the list boxes successfully. no errors showing, ready to merge pull request.

**Pull request merged**
